log_file = /var/log/audit/audit.log
log_format = RAW
max_log_file = 50
max_log_file_action = ROTATE
num_logs = 5
space_left = 75
space_left_action = SYSLOG
admin_space_left = 50
admin_space_left_action = SUSPEND
