[package]
name = "common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Common types and utilities shared across ESP crates"

[features]
default = ["attestation"]
attestation = ["dep:openssl"]
full-results = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = { version = "0.10", optional = true }
